# Unix submit description file
getenv                  = True
executable              = $EXE_NAME$.sh
#RequestRuntime=60
#RequestMemory = 600
#request_memory          = 10
log                     = $EXE_NAME$.log
output                  = $EXE_NAME$.o
error                   = $EXE_NAME$.err
environment             = "LD_LIBRARY_PATH_STORED=$LD_LIBRARY_PATH$:$LHAPDF_DATA_PATH$"
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue
