# Unix submit description file

+RequestRuntime=60
#RequestMemory = 600
request_memory          = 10
executable              = $EXE_NAME$.csh
log                     = $EXE_NAME$.log
output                  = $EXE_NAME$.out
error                   = $EXE_NAME$.err
getenv                  = True
environment             = "LD_LIBRARY_PATH_STORED=$LD_LIBRARY_PATH$"
should_transfer_files   = Yes
when_to_transfer_output = ON_EXIT
queue
